substitutions:
  devicename: bedroom
  upper_devicename: bedroom

esphome:
  name: "${devicename}"
esp32:
 board: wemos_d1_mini32 #lolin_s2_mini

logger:

api:
  password: !secret api_pass
  
ota:
  password: !secret ota_pass

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass


  ap:
    ssid: "${devicename} Fallback"
    password: !secret back_pass

captive_portal:

sun:
  latitude: xxxx
  longitude: xxxx
  
i2c:
   sda: D2 #21
   scl: D1 #22
   scan: true



remote_transmitter:
  pin: D5 #18
  carrier_duty_percent: 50%
  
 
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${upper_devicename} IP Address"
    ssid:
      name: "${upper_devicename} SSID"
    mac_address:
      name: "${upper_devicename} Mac"

sensor:
  - platform: aht10
    temperature:
      name: "${upper_devicename} T"
      id: bedroom_t
      filters:
        - calibrate_linear:
          - 0.0 -> 0.0
          - 28.0 -> 23.7
    humidity:
      name: "${upper_devicename} humidity"
      id: bedroom_h
      filters:
        - calibrate_linear:
          - 0.0 -> 0.0
          - 36.0 -> 42
    update_interval: 60s
    address: 0x38
  
  - platform: template
    name: "${upper_devicename} brightness"
    id: brightness
    lambda: |-
      if (id(i_clock).state > 24) {
        return 7;
      } else {
       if (id(i_clock).state > 20) {
        return 6;
      } else {
       if (id(i_clock).state > 16) {
        return 5;
      } else {
       if (id(i_clock).state > 12) {
        return 4;
      } else {  
       if (id(i_clock).state > 8) {
        return 3;
      } else {
       if (id(i_clock).state > 4) {
        return 2;
      } else {
      if (id(i_clock).state > 1) {
        return 1;
      } else {
       return 0 ;}}}}}}}
    update_interval: 5s
    
  - platform: bh1750
    name: "${upper_devicename} Illuminance"
    id: i_clock
    address: 0x23
    update_interval: 10s
    
  - platform: sgp30
    eco2:
      name: ${upper_devicename} eCO2
      accuracy_decimals: 1
      id: bedroom_eCO2
      filters:
       - max:
          window_size: 4
          send_every: 60
    tvoc:
      name: ${upper_devicename} TVOC
      accuracy_decimals: 1
      id: bedroom_TVOC
      filters:
       - max:
          window_size: 4
          send_every: 60
    store_baseline: yes
    address: 0x58
    update_interval: 1s
    compensation:
      temperature_source: bedroom_t
      humidity_source: bedroom_h
    baseline:
      eco2_baseline: 0xXXXX
      tvoc_baseline: 0xXXXX
      
  - platform: wifi_signal
    name: ${upper_devicename} Wifi
    update_interval: 60s
    

  - platform: sun
    name: "${upper_devicename} Elevation"
    type: elevation
    id: elevation
    
display:
  - platform: tm1637
    id: tm1637_c
    clk_pin: D0 #26
    dio_pin: D6 #19
    update_interval: 500ms
    lambda: |-
      it.set_intensity(static_cast<int>(id(brightness).state));
      static int i = 0;
      i++;
      if ((i % 2) == 0)
        it.strftime("%H.%M", id(sntp_time).now());
      else
        it.strftime("%H%M", id(sntp_time).now()); 
      it.printf(4,"%.0f." , id(bedroom_h).state);
      
  - platform: tm1637
    id: tm1637_t
    clk_pin: D0 #26
    dio_pin: D7 #23
    update_interval: 500ms
    lambda: |-
      it.set_intensity(static_cast<int>(id(brightness).state));
      it.printf( "%0.0f.c" , id(bedroom_t).state);
      if ((id(elevation).state) > 0)
        it.printf(3,"~");
#      else
#        it.printf(3,"_");       
media_player:
  - platform: i2s_audio
    name: ${devicename}
    dac_type: external
    i2s_lrclk_pin: 27
    i2s_dout_pin: 25
    i2s_bclk_pin: 32
    mode: mono
    id: clok
    mute_pin:
      number: 12 # GAIN Connected to VDD 100kΩ resistor 3db(6db VDD) Connected to GND 100kΩ resistor 15db (12db GND)
      inverted: true

switch: 
  - platform: gpio
    pin:
      number: 2 # internal
      inverted: false
    id: ledRF
  - platform: template
    name: RF Power Button1
    turn_on_action:
      - switch.turn_on: ledRF
      - remote_transmitter.transmit_rc_switch_raw:
          code: '0000101001101001001001000'
          protocol: 1
          repeat: 
            times: 2
            wait_time: 20ms
      - switch.turn_off: ledRF
  - platform: template
    name: RF Power Button2
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '0101110111000111111100000'
          protocol: 1
          repeat: 
            times: 2
            wait_time: 20ms
  - platform: template
    name: RF Power Button3
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '0101110111000111001100000'
          protocol: 1
          repeat: 
            times: 2
            wait_time: 20ms
  - platform: template
    name: RF Power Button OFF
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '0101110111000111110000000'
          protocol: 1
          repeat: 
            times: 2
            wait_time: 20ms
            

web_server:
  port: 80
  auth:
    username: !secret web_user
    password: !secret web_pass

time:
  - platform: sntp
    id: sntp_time
    timezone: "MSK-2MSD,M3.5.0/2,M10.5.0/3"
    servers: 192.168.88.xx
