##########################################
##           WEMOS D1 mini              ##
##  |RS|          |#|     | 1|          ##
##  |A0|          |#|     | 3|          ##
##  |D0|          |#|     |D1| scl      ##
##  |D5|          |#|     |D2| sda      ##
##  |D6|          |#|     |D3| DIO      ##
##  |D7|          |#|     |D4| CLK      ##
##  |D8|          |#|     |GN|          ## 
##  |3V|          |#|     |5V|          ##
##########################################

substitutions:
  name: "clock-g"
  device_description: "Часы для Гришы"
  
esphome:
  name: "${name}"
  comment: "${device_description}"
  on_boot:
    then:
      ds1307.read_time:
        
esp8266:
  board: d1_mini

i2c:
   sda: D2
   scl: D1
   scan: true

ota:
  - platform: esphome
    password: !secret ota_pass 
  - platform: web_server
  
wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: Wi-Fi
      password: konvoy4071
  min_auth_mode: WPA2
  ap:
    ssid: "clock-Wi-Fi"    
    password: konvoy4071

captive_portal:
  
time:
  - platform: ds1307
    id: rtc_time
    update_interval: never

  - platform: sntp
    id: sntp_time
    timezone: Europe/Moscow
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org
    on_time_sync:
      then:
        ds1307.write_time:
    on_time:
      - hours: 0
        minutes: 0
        seconds: 0
        then:
          ds1307.write_time:

display:
  - platform: tm1637
    id: tm1637_c
    clk_pin: D4
    dio_pin: D3
    update_interval: 1s
    lambda: |-
      static int i = 0;
      i++;
      if ((i % 2) == 0)
        it.strftime("%H.%M", id(rtc_time).now());
      else
        it.strftime("%H%M", id(rtc_time).now());  
    